<%@page import="java.io.*" %>
<%@page import="javax.script.*" %>
<%@page import="php.java.script.servlet.EngineFactory" %>

<%!
private static File script;
private static File getScript(String path) {
  if(script!=null) return script;
  return script=EngineFactory.getPhpScript(path, 
    new StringReader(
      "<?php function f($arg) {return 1 + (int)(string)$arg; }; ?>"));
}
%>
<%
try {
ScriptEngine e = 
  EngineFactory.getInvocablePhpScriptEngine (this,
                               application, request, response, "http", 80);
e.getContext().setWriter (out);

File script = getScript(application.getRealPath(request.getServletPath()));
FileReader reader = EngineFactory.createPhpScriptFileReader(script);
e.eval (reader); reader.close();
Object result=((Invocable)e).invokeFunction("f", new Object[]{new Integer(2)});
e.eval ((Reader)null); // flush the output generated by invokeXXX
out.println("result from php::f(), printed from the servlet: " + result);
} catch (Exception ex) {
  out.println("Could not evaluate script on IIS/Apache port 80: "+ex);
}
%>
