<%

javax.script.ScriptEngine e = 
  php.java.script.servlet.EngineFactory.getInvocablePhpScriptEngine (this, 
                                                    application, 
                                                    request, 
                                                    response);
e.getContext().setWriter (out);

e.eval ("<?php function f($arg) {return 1 + java_values($arg); }; ?>");

javax.script.Invocable i = (javax.script.Invocable) e;

Object result = null;
result = i.invokeFunction("phpinfo", new Object[]{});
result = i.invokeFunction("f", new Object[]{new Integer(2)});

// note that we have to flush the generated output, othewise the output
// from the servlet will appear at the beginning of the page or somewhere
// in between

e.eval ((java.io.Reader)null); // flush the output generated by invokeXXX

out.println("result from php::f(), printed from the servlet: " + result);

%>
