# the PHP tests generated by phpize
m4_include(../acinclude.m4)
# the java tests generated by configure
syscmd([here=`pwd`;cd ../tests.m4;cat `echo *.m4` >$here/java_tests.m4;cd ..])
m4_include(java_tests.m4)
