# the PHP tests generated by phpize
m4_include(../acinclude.m4)
# the java tests
sinclude(../tests.m4/function_checks.m4)
sinclude(../tests.m4/threads.m4)
sinclude(../tests.m4/java_check_broken_stdio_buffering.m4)
sinclude(../tests.m4/java_check_broken_gcc_installation.m4)

